---
title: "Overview"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# What this Package Does

The `DSbulkUploadR` package only requires using two R functions: 
`write_input_template()` creates an excel spreadsheet (DSbulkUploadR_input.xlsx) with a separate sheet for each supported reference type. After the .xlsx file is populated, a second function `generate_references()` takes the data in the input.xlsx file and uses it to perform the bulk upload. The bulk upload consists of:

1) Data validation
3) Create draft reference(s) on DataStore
4) Populate each draft reference with the supplied information
5) Optionally, upload **all** the file(s) in the specified directory to the draft reference(s)
6) Connect your reference to a pre-existing DataStore Project reference
7) Optionally, activate each reference

The `generate_references()` will invisibly return a dataframe containing all of the information supplied in the input .xlsx file with two additional columns containing the datastore reference ID for each newly created reference and the status of the newly created reference ("draft" or "active"). You may wish to write this dataframe to a .csv, .txt, or similar for your records.

Should you choose to leave references in a draft status using `generate_references` (for instance to provide an opportunity for review prior to publication) you can subsequently and independently activate them by passing the reference ids in the resulting data frame to the `activate_references` function.

# What this Package Doesn't
1) Connect to the VPN or to the NPS network for you (you must be connected to the network to use these functions)
2) Register ORCiDs for authors.
3) Add an author's ORCID to their Active Directory/Entra ID account
4) Provide peer, technical, administrative, or other review of the reference(s) created
5) Add taxonomy to the reference(s)

# Supported DataStore Reference Types
1) Audio Recording
2) Generic Document
3) Web Site
4) Generic Dataset
5) Field Notes *
6) Script
7) Project

* Field Notes are not an actual reference type on DataStore. Information supplied as "Field Notes" to DSbulkUploadR will be treated as a Generic Document with the exception that the keyword "FieldNotes" will be added to the GenericDocument for triage at a later date. 

# Supported File Types
Upload of all file types is supported. There is no distinction made among file types and no need to designate specific file types. Changing the default settings can result in virtually limitless numbers and sizes of files to upload. Use caution when changing the default settings!

